name: Essence Table Check

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    env:
      ESSENCE_DIR: ~/EssenceCatalog
      CONJURE_DIR: ~/conjure-v2.5.0-linux
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Download conjure binary as zip file from Releases
        run: wget https://github.com/conjure-cp/conjure/releases/download/v2.5.0/conjure-v2.5.0-linux.zip

      - name: Extract conjure binary
        run: mkdir $CONJURE_DIR
             unzip conjure-v2.5.0-linux.zip -d $CONJURE_DIR
             ls $CONJURE_DIR

      - name: Get conjure version
        run: $CONJURE_DIR/conjure --version

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
        working-directory: ./
